# -*- mode: python ; coding: utf-8 -*-


block_cipher = None


a = Analysis(['GandalfDance.py'],
             pathex=[],
             binaries=[],
             datas=[
				('Files/bgMenu.png','Files'),
				('Files/bgCredits.png','Files'),
				('Files/bgPause.png','Files'),
				('Files/bgChoose.png','Files'),
				('Files/bgGame1.png','Files'),
				('Files/bgGameUp.png','Files'),
				('Files/bgGameOver.png','Files'),
				('Files/bgWinNext.png','Files'),
				('Files/bgWin.png','Files'),
				('Files/bgTutorial1.png','Files'),
				('Files/bgTutorial2.png','Files'),
				('Files/bgGameEnd.png','Files'),
				('Files/bgSaveF.png','Files'),
				('Files/bgSaveT.png','Files'),
				('Files/button1.png','Files'),
				('Files/button2.png','Files'),
				('Files/button3.png','Files'),
				('Files/buttonYes.png','Files'),
				('Files/buttonNo.png','Files'),
				('Files/lvl1.png','Files'),
				('Files/lvl2.png','Files'),
				('Files/lvl3.png','Files'),
				('Files/back.png','Files'),
				('Files/lvl2block.png','Files'),
				('Files/lvl3block.png','Files'),
				('Files/note.png','Files'),
				('Files/click.png','Files'),
				('Files/click2.png','Files'),
				('Files/G01.png','Files'),
				('Files/G03.png','Files'),
				('Files/save.txt','Files'),
				('Files/lvl1.txt','Files'),
				('Files/lvl2.txt','Files'),
				('Files/lvl3.txt','Files'),
				('Files/pixel.ttf','Files'),
				('Files/Epic Sax Guy - 8-bit Remix.mp3','Files'),
				('Files/music.mp3','Files'),
				('Files/sound.wav','Files'),
				('Files/Game Over.mp3','Files'),
				('Files/HeatleyBros - 8 Bit Win.mp3','Files')
			 ],
             hiddenimports=[],
             hookspath=[],
             hooksconfig={},
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)

exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,  
          [],
          name='GandalfDance',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          upx_exclude=[],
          runtime_tmpdir=None,
          console=False,
          disable_windowed_traceback=False,
          target_arch=None,
          codesign_identity=None,
          entitlements_file=None )
